services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_inventory_web
    command: sleep infinity
    ports:
      - "18000:8000"
    volumes:
      - ./smart_inventory_be:/app
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: smart_inventory_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    build:
      context: ./smart_inventory_fe
      dockerfile: Dockerfile-nodejs
    image: smart-inventory-frontend-node-apache
    container_name: smart_inventory_frontend
    user: "root"
    working_dir: /var/www/html/smart_inventory_fe
    volumes:
      - ./smart_inventory_fe:/var/www/html/smart_inventory_fe
      - ./smart_inventory_fe/apache:/etc/apache2/sites-available
    environment:
      - NODE_ENV=development
    ports:
      - "23010:3000"
    expose:
      - "80"
      - "3000"
    command: apache2ctl -D FOREGROUND
    restart: always


volumes:
  pgdata:

